cloudMapperMsg: {

    lowerBound: -24.8,
    upperBound:  2.0,
    nScanRings:  64,
}


binReaderMsg: {
    binDir: "your_path_to_data",
    frameNum: 428,
}

groundSegmentationMsg: {
    segThres: 0.35,
}

featurePointsMsg: {
    heightMaxThres: 0.5,
    heightMinThres: 0.02,
    heightRegion: 5,
    heightSigmaThre: 0.01,

    curvatureRegion: 5,
    curvatureThres: 0.001,

    distanceHorizonThres: 2.0,
    distanceVerticalThres: 0.0,

    angularRes: 0.16,

    useVerticle: false,
    useHorizon: true,
}

boundaryPointsMsg: {

    varThres: 2.5,
    meanThres: 1.5,
    gridNum: 200,
    gridRes: 0.5,
    curveFitThres: 0.15,
    useCurveRansac: true,
}